apiVersion: v1
kind: Service
metadata:
  name: dotnet-rate-limit-service
spec:
  selector:
    app: dotnet-rate-limit
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer